
name: CI

on:
  push:
    tags: [ "*" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: azqaz/tvm-build-rpi:crossrpi

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - run: |
          sh build_rpi_runtime.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            install.rpi/*

      
